version: '3.8'
services:
  movies:
     image: unlimiteddba/paytmmovies:latest
      ports:
        - "81:80"
      volumes:
        - "movies01"
      deploy:
         replicas: 3
   train:
     image: unlimiteddba/paytmtrain:latest
      ports:
        - "82:80"
      volumes:
        - "train01"
      deploy:
         replicas: 3
   dth:
     image: unlimiteddba/paytmdth:latest
      ports:
        - "83:80"
      volumes:
        - "dth01"
      deploy:
         replicas: 3
   recharge:
     image: unlimiteddba/paytrecharge:latest
      ports:
        - "84:80"
      volumes:
        - "recharge01"
      deploy:
         replicas: 3
