version: '3.8'
services:
  movies:
    image : unlimitteddba/paytmmovies:latest
    ports:
      - "81:80"
    volmes:
      - "devopsvol1"
    deploy:
      replicas: 3

   train:
    image : unlimitteddba/paytmtrains:latest
    ports:
      - "82:80"
    volmes:
      - "devopsvol2"
    deploy:
      replicas: 3

    dth:
    image : unlimitteddba/paytmdth:latest
    ports:
      - "83:80"
    volmes:
      - "awsvol1"
    deploy:
      replicas: 3


    recharge:
    image : unlimitteddba/paytmdthrecharge:latest
    ports:
      - "84:80"
    volmes:
      - "awsvol2"
    deploy:
      replicas: 3
